#https://book.orthanc-server.com/faq/scalability.html#scalability-memory
---
apiVersion: v1
kind: Service
metadata:
  name: orthanc-web
spec:
  ports:
  - name: orthanc-web
    protocol: TCP
    port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: orthanc-dicom
spec:
  ports:
  - name: orthanc-dicom
    protocol: TCP
    port: 4242
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: orthanc
spec:
  rules:
  - host: orthanc.somedomain.ch
    http:
      paths:
      - backend:
          serviceName: orthanc-web
          servicePort: orthanc-web
        path: /
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: orthanc-config-cm
data:
  DICOM_MODALITIES: '{ "Befundungsstation" : [ "BAG_MONITOR", "192.168.0.8", 11112 ], "FINDSCU-UTILITY": [ "FINDSCU", "10.42.0.1", 104 ] }'
  AC_REGISTERED_USERS: '{ "orthanc": "orthanc" }'
  PEERS: '{"orthanc-peer" : [ "http://c0100-peer.curapacs.ch" ]}'
  HTTP_PORT: "8080"
  PG_ENABLED: "true"
  PG_HOST: "orthanc-postgres"
  PG_DB: "orthanc"
  PG_USER: "orthanc"
  PG_PASSWORD: "orthanc"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc-deployment
spec:
  replicas: 1
  template:
    spec:
      automountServiceAccountToken: false
      containers:
        - name: orthanc
          image: osimis/orthanc
          envFrom:
            - configMapRef:
                name: orthanc-config-cm
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Zurich
