#https://book.orthanc-server.com/faq/scalability.html#scalability-memory
---
apiVersion: v1
kind: Service
metadata:
  name: orthanc-web
spec:
  ports:
  - name: orthanc-web
    protocol: TCP
    port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: orthanc-ws
spec:
  ports:
  - name: orthanc-ws
    protocol: TCP
    port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: orthanc-dicom
spec:
  ports:
  - name: orthanc-dicom
    protocol: TCP
    port: 4242
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: orthanc
spec:
  rules:
  - host: orthanc.somedomain.ch
    http:
      paths:
      - backend:
          serviceName: orthanc-web
          servicePort: orthanc-web
        path: /
      - backend:
          serviceName: orthanc-ws
          servicePort: orthanc-ws
        path: /ws
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: orthanc-config-cm
data:
  ORTHANC__NAME: "CURAPACS"
  HTTP_PORT: "8080"
  POSTGRESQL_PLUGIN_ENABLED: "true"
  ORTHANC__POSTGRESQL__HOST: "orthanc-postgres-CURAPACS_CUSTOMER" 
  ORTHANC__POSTGRESQL__DATABASE: "orthanc"
  ORTHANC__POSTGRESQL__USER: "orthanc"
  ORTHANC__POSTGRESQL__PASSWORD: "orthanc"
  PYTHON_PLUGIN_ENABLED: "true"
  ORTHANC__PYTHON_SCRIPT: "/usr/local/share/orthanc/plugins/python/main.py"
  WORKLISTS_PLUGIN_ENABLED: "true"
  ORTHANC__REGISTERED_USERS: '{"orthanc": "orthanc"}'
  ORTHANC__DICOM_MODALITIES: '{"Befundungsstation" : [ "BAG_MONITOR", "192.168.0.8", 11112 ], "FINDSCU-UTILITY": ["FINDSCU", "10.42.0.1", 104]}'
  ORTHANC__ORTHANC_PEERS: '{"orthanc-peer": [ "http://c0100-peer.curapacs.ch" ]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc-deployment
spec:
  replicas: 1
  template:
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 101
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      initContainers:
        - name: init-fetch-python-scripts
          image: alpine
          command: ['ash', '-c', 'apk update && apk add --no-cache git && cd /tmp && git clone -b feature/orthanc_peering https://github.com/elly2178/lc2_curapacs.git && cd /tmp/lc2_curapacs/orthanc-plugins && mv main.py curapacs-python/ /mnt/curapacs-python-plugins && chmod -R 775 /mnt/curapacs-python-plugins']
          volumeMounts:
            - name: curapacs-python-plugins-vol
              mountPath: /mnt/curapacs-python-plugins
      containers:
        - name: orthanc
          image: osimis/orthanc
          envFrom:
            - configMapRef:
                name: orthanc-config-cm
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: curapacs-plugins-vol
              mountPath: /usr/local/share/orthanc/plugins/python/
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Zurich
        - name: curapacs-python-plugins-vol
          emptyDir: {}
