---
apiVersion: v1
kind: Service
metadata:
  name: orthanc-postgres
  namespace: curapacs
  labels:
    app.kubernetes.io/name: orthanc-postgres
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: curapacs-provisioner
    curamed.ch/customer: c0100
spec:
  selector:
    app.kubernetes.io/name: orthanc-postgres
    curamed.ch/customer: c0100
  ports:
    - name: orthanc-postgres
      protocol: TCP
      port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc-postgres-deployment
  namespace: curapacs
  labels:
    app.kubernetes.io/name: orthanc-postgres
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: curapacs-provisioner
    curamed.ch/customer: c0100
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orthanc-postgres
      app.kubernetes.io/version: "1.0"
      app.kubernetes.io/managed-by: curapacs-provisioner
      curamed.ch/customer: c0100
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orthanc-postgres
        app.kubernetes.io/version: "1.0"
        app.kubernetes.io/managed-by: curapacs-provisioner
        curamed.ch/customer: c0100
    spec:
      automountServiceAccountToken: false
      containers:
        - name: orthanc-postgres
          image: postgres:9.6
          env:
            - name: "POSTGRES_DB"
              value: "orthanc"
            - name: "POSTGRES_USER"
              value: "orthanc"
            - name: "POSTGRES_PASSWORD"
              value: "orthanc"
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Zurich
