---
apiVersion: v1
kind: Service
metadata:
  name: meddream-tokenservice
spec:
  ports:
    - name: meddream-tokenservice
      protocol: TCP
      port: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meddream-tokenservice-application-properties-cm 
data:
  application.properties: |-
    server.port=80
    com.softneta.token.one-time-token=false
    logging.level.root=DEBUG
    security.generate.ip-white-list=10.21.1.12;10.21.1.13
    security.validate.ip-white-list=10.21.1.12;10.21.1.13
    #security.generate.ip-white-list=his
    #security.validate.ip-white-list=meddream
    security.user.name=orthanc
    security.user.password=orthanc
    management.context-path=/manage 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: meddream-tokenservice
spec:
  rules:
  - host: meddream-tokenservice.somedomain.ch
    http:
      paths:
      - backend:
          serviceName: meddream-tokenservice
          servicePort: meddream-tokenservice
        path: /
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meddream-tokenservice-deployment
spec:
  replicas: 1
  template:
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 101
      containers:
        - name: meddream-tokenservice
          image: meddream/token-service
          volumeMounts:
            - name: meddream-tokenservice-application-properties-vol
              mountPath: /opt/token/application.properties
              subPath: application.properties
